const cfg = require("./site-config");

function esc(s) {
  return String(s == null ? "" : s).replace(/[&<>"']/g, (c) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
  }[c]));
}

function navHtml(activePath) {
  return cfg.nav
    .map((item) => {
      const isActive = activePath && item.href.replace(/^\//, "").startsWith(activePath);
      return `<a class="link${isActive ? " is-active" : ""}" href="${item.href}">${esc(item.label)}</a>`;
    })
    .join("\n      ");
}

function header(activePath) {
  return `<header class="topbar">
  <div class="wrap topbar__inner">
    <a href="/#top" class="brand" aria-label="Silver Signal home">
      <span class="mark" aria-hidden="true"></span>
      <span>Silver <em>Signal</em></span>
    </a>
    <nav class="topnav" aria-label="Primary">
      ${navHtml(activePath)}
    </nav>
    <div class="topnav-actions">
      <a class="cta" href="/contact/">Book Audit</a>
    </div>
  </div>
</header>`;
}

function footer() {
  return `<footer class="foot">
  <div class="wrap">
    <div class="foot__top">
      <div>
        <div class="foot__brand">Silver <em>Signal</em></div>
        <div class="foot__tag">RevOps for Personal Injury Law Firms</div>
        <p class="foot__addr">
          ${esc(cfg.address.line1)}<br/>
          ${esc(cfg.address.line2)}<br/>
          ${esc(cfg.address.line3)}
        </p>
      </div>
      <div class="foot__col">
        <h4>Site</h4>
        <ul>
          <li><a href="/#problem">The Gap</a></li>
          <li><a href="/#how">Approach</a></li>
          <li><a href="/#case">Case Study</a></li>
          <li><a href="/#work">How We Work</a></li>
          <li><a href="/#faq">FAQ</a></li>
          <li><a href="/blog/">Blog</a></li>
        </ul>
      </div>
      <div class="foot__col">
        <h4>Contact</h4>
        <ul>
          <li><a href="mailto:${esc(cfg.contactEmail)}">${esc(cfg.contactEmail)}</a></li>
          <li><a href="/contact/">Book a call</a></li>
          <li><a href="${cfg.linkedin}" target="_blank" rel="noopener">LinkedIn</a></li>
        </ul>
      </div>
      <div class="foot__col">
        <h4>Legal</h4>
        <ul>
          <li><a href="/privacy/">Privacy</a></li>
          <li><a href="/terms/">Terms</a></li>
          <li><a href="/cookies/">Cookies</a></li>
        </ul>
      </div>
    </div>
    <div class="foot__bottom">
      <span>&copy; <span id="year"></span> Silver Signal Ltd &middot; Registered in England &amp; Wales</span>
      <span>All figures in USD unless stated</span>
    </div>
  </div>
</footer>`;
}

/**
 * Google Analytics 4 with Consent Mode v2.
 *
 * Every consent signal starts as "denied", so GA loads but stores nothing
 * until the visitor accepts the banner in /scripts/site-cookies.js. Keep this
 * in sync with the same block hand-written into index.html, which is not
 * generated by this template.
 */
function analyticsHead() {
  if (!cfg.gaMeasurementId) return "";
  const id = cfg.gaMeasurementId;
  return `<script async src="https://www.googletagmanager.com/gtag/js?id=${id}"></script>
<script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('consent','default',{ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied',analytics_storage:'denied',wait_for_update:500});gtag('config','${id}',{anonymize_ip:true});</script>
<script defer src="/scripts/site-cookies.js"></script>`;
}

function baseScripts() {
  return `<script>
document.getElementById("year").textContent = new Date().getFullYear();
</script>`;
}

/**
 * Renders a full HTML document using the shared shell (head, header, footer).
 * Every generated page (contact, blog index, blog posts) goes through this
 * so SEO tags and schema stay consistent by construction.
 */
function shell({
  title,
  description,
  path, // e.g. "/contact/" — used for canonical + og:url
  activeNav, // "blog" | "contact" | undefined
  ogImage,
  ogType = "website",
  jsonLd = [], // array of objects, each rendered as its own <script type="application/ld+json">
  extraHead = "",
  bodyHtml,
  extraScripts = "",
  noindex = false, // true for pages that shouldn't rank (e.g. the post-booking thank-you page)
}) {
  const canonical = `${cfg.siteUrl}${path}`;
  const image = ogImage || cfg.ogImage;
  const jsonLdBlocks = jsonLd
    .map((obj) => `<script type="application/ld+json">${JSON.stringify(obj, null, 2)}</script>`)
    .join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover" />
<title>${esc(title)}</title>
<meta name="description" content="${esc(description)}" />
<meta name="theme-color" content="#F4F4F9" />
${noindex ? '<meta name="robots" content="noindex,follow" />\n' : ""}<link rel="canonical" href="${canonical}" />
<link rel="icon" href="/favicon.svg" type="image/svg+xml" />
<link rel="icon" href="/images/logo.png" sizes="512x512" />

<meta property="og:site_name" content="${esc(cfg.siteName)}" />
<meta property="og:title" content="${esc(title)}" />
<meta property="og:description" content="${esc(description)}" />
<meta property="og:type" content="${esc(ogType)}" />
<meta property="og:url" content="${canonical}" />
<meta property="og:image" content="${image}" />
<meta property="og:image:width" content="1200" />
<meta property="og:image:height" content="630" />
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:title" content="${esc(title)}" />
<meta name="twitter:description" content="${esc(description)}" />
<meta name="twitter:image" content="${image}" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700&family=Geist+Mono:wght@400;500&display=swap" rel="stylesheet">
<link rel="stylesheet" href="/styles/site.css" />
${analyticsHead()}
${jsonLdBlocks}
${extraHead}
</head>
<body>
${header(activeNav)}
<main id="top">
${bodyHtml}
</main>
${footer()}
${baseScripts()}
${extraScripts}
</body>
</html>
`;
}

module.exports = { shell, esc, header, footer, analyticsHead, cfg };
